### ISSUE TITLE
SstemStackError333 stack too deep - 489177792

### ISSUE THREAD

**Issue by leo-martin** [leo-martin/test#82]
## Environment: test
SstemStackError333 stack too deep - 489177792

`app/models/shipment/masterboxed.rb in any? at line 29`

https://sentry.io/shoprunback/web_production/issues/584577173

**Comment by leo-martin** [comment]
@leo-test-github

**Comment by PaulGirardin** [comment]
Test
zjhdahd
41

@leo-test-github 

aiais
@leo-martin @leo-martin @leo-test-github 

ajdiajd45z4dz5dzd?
@sjiasasd

**Comment by PaulGirardin** [comment]
Test
zjhdahd
41

@leo-test-github

aiais
@leo-martin @leo-martin @leo-test-github

ajdiajd45z4dz5dzd?
@sjiasasd

**Comment by PaulGirardin** [comment]
Test
zjhdahd
41

@leo-test-github

aiais
@leo-martin @leo-martin @leo-test-github

ajdiajd45z4dz5dzd?
@sjiasasd

**Comment by PaulGirardin** [comment]
@leo-martin 
@PaulGirardin
@sjiasasd

**Comment by leo-martin** [comment]
@leo-test-github

**Comment by leo-martin** [comment]
@leo-test-github

**Comment by leo-martin** [comment]
@leo-test-github

**Comment by leo-martin** [comment]
@leo-test-github

**Comment by leo-martin** [comment]
@leo-test-github

**Comment by leo-martin** [comment]
@leo-martin

**Comment by PaulGirardin** [comment]
@leo-martin

**Comment by PaulGirardin** [comment]
@leo-martin @random n'importe quoi
